version: 2
registries:
  git-github-io:
    type: git
    url: https://github.io
    username: jpelaezClub
    password: "${{secrets.GIT_GITHUB_IO_PASSWORD}}"
  git-wordpress-com:
    type: git
    url: https://wordpress.com
    username: jpelaezblog01
    password: "${{secrets.GIT_WORDPRESS_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.447.0
    - 1.448.0
    - 1.449.0
    - 1.452.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.460.0
    - 1.462.0
    - 1.464.0
    - 1.466.0
    - 1.467.0
    - 1.471.0
    - 1.474.0
    - 1.476.0
    - 1.483.0
    - 1.486.0
    - 1.488.0
    - 1.491.0
    - 1.495.0
    - 1.503.0
    - 1.509.0
    - 1.511.0
    - 1.520.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.532.0
    - 1.538.0
    - 1.563.0
    - 1.566.0
    - 1.570.0
  - dependency-name: date-fns
    versions:
    - 2.16.1
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
    - 2.20.1
    - 2.20.2
    - 2.20.3
    - 2.21.0
  - dependency-name: gatsby-cli
    versions:
    - 2.18.0
    - 2.19.0
    - 2.19.1
    - 2.19.2
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/standalone"
    versions:
    - 7.12.12
    - 7.12.15
    - 7.12.16
    - 7.12.18
    - 7.13.10
    - 7.13.11
    - 7.13.12
    - 7.13.14
    - 7.13.15
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: stripe
    versions:
    - 8.132.0
    - 8.133.0
    - 8.134.0
    - 8.135.0
    - 8.136.0
    - 8.137.0
    - 8.138.0
    - 8.139.0
    - 8.140.0
    - 8.141.0
    - 8.142.0
  - dependency-name: d3
    versions:
    - 6.5.0
    - 6.6.0
    - 6.6.1
    - 6.6.2
  - dependency-name: faker
    versions:
    - 5.2.0
    - 5.3.1
    - 5.4.0
    - 5.5.1
    - 5.5.2
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.13.0
    - 7.13.14
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: "@babel/node"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
  - dependency-name: nanoid
    versions:
    - 3.1.20
    - 3.1.21
  - dependency-name: connect-mongo
    versions:
    - 4.1.0
    - 4.2.0
    - 4.2.2
    - 4.3.0
    - 4.3.1
    - 4.4.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.5
    - 2.32.8
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: "@commitlint/travis-cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: express-validator
    versions:
    - 6.10.0
    - 6.9.2
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
  - dependency-name: rollbar
    versions:
    - 2.19.4
    - 2.20.0
    - 2.21.0
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: rss-parser
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: pm2
    versions:
    - 4.5.1
    - 4.5.4
    - 4.5.5
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 3.12.0
  - dependency-name: react-reflex
    versions:
    - 3.1.1
  - dependency-name: gatsby-plugin-create-client-paths
    versions:
    - 2.9.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/free-regular-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: hast-util-select
    versions:
    - 4.0.2
  - dependency-name: loopback-connector-mongodb
    versions:
    - 5.5.0
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: hast-util-to-html
    versions:
    - 7.1.2
  - dependency-name: joi
    versions:
    - 17.3.0
  - dependency-name: "@babel/plugin-proposal-export-default-from"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-proposal-function-bind"
    versions:
    - 7.12.1
  - dependency-name: rehype-raw
    versions:
    - 5.0.0
  registries:
  - git-github-io
  - git-wordpress-com
